// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// AuthToken auth token
// swagger:model AuthToken
type AuthToken string

// Validate validates this auth token
func (m AuthToken) Validate(formats strfmt.Registry) error {
	return nil
}
