// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetTaskStatusHandlerFunc turns a function with the right signature into a get task status handler
type GetTaskStatusHandlerFunc func(GetTaskStatusParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTaskStatusHandlerFunc) Handle(params GetTaskStatusParams) middleware.Responder {
	return fn(params)
}

// GetTaskStatusHandler interface for that can handle valid get task status params
type GetTaskStatusHandler interface {
	Handle(GetTaskStatusParams) middleware.Responder
}

// NewGetTaskStatus creates a new http.Handler for the get task status operation
func NewGetTaskStatus(ctx *middleware.Context, handler GetTaskStatusHandler) *GetTaskStatus {
	return &GetTaskStatus{Context: ctx, Handler: handler}
}

/*GetTaskStatus swagger:route GET /tasks/{id} getTaskStatus

Get status of the task

*/
type GetTaskStatus struct {
	Context *middleware.Context
	Handler GetTaskStatusHandler
}

func (o *GetTaskStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTaskStatusParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
