// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/crxfoz/seo_metrick_parser/server/api/models"
)

// GetTaskDataOKCode is the HTTP code returned for type GetTaskDataOK
const GetTaskDataOKCode int = 200

/*GetTaskDataOK OK

swagger:response getTaskDataOK
*/
type GetTaskDataOK struct {

	/*
	  In: Body
	*/
	Payload []*models.URLResult `json:"body,omitempty"`
}

// NewGetTaskDataOK creates GetTaskDataOK with default headers values
func NewGetTaskDataOK() *GetTaskDataOK {

	return &GetTaskDataOK{}
}

// WithPayload adds the payload to the get task data o k response
func (o *GetTaskDataOK) WithPayload(payload []*models.URLResult) *GetTaskDataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get task data o k response
func (o *GetTaskDataOK) SetPayload(payload []*models.URLResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTaskDataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.URLResult, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetTaskDataNotFoundCode is the HTTP code returned for type GetTaskDataNotFound
const GetTaskDataNotFoundCode int = 404

/*GetTaskDataNotFound Task id not found

swagger:response getTaskDataNotFound
*/
type GetTaskDataNotFound struct {
}

// NewGetTaskDataNotFound creates GetTaskDataNotFound with default headers values
func NewGetTaskDataNotFound() *GetTaskDataNotFound {

	return &GetTaskDataNotFound{}
}

// WriteResponse to the client
func (o *GetTaskDataNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetTaskDataBadGatewayCode is the HTTP code returned for type GetTaskDataBadGateway
const GetTaskDataBadGatewayCode int = 502

/*GetTaskDataBadGateway database is down

swagger:response getTaskDataBadGateway
*/
type GetTaskDataBadGateway struct {
}

// NewGetTaskDataBadGateway creates GetTaskDataBadGateway with default headers values
func NewGetTaskDataBadGateway() *GetTaskDataBadGateway {

	return &GetTaskDataBadGateway{}
}

// WriteResponse to the client
func (o *GetTaskDataBadGateway) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(502)
}
