// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetTaskDataHandlerFunc turns a function with the right signature into a get task data handler
type GetTaskDataHandlerFunc func(GetTaskDataParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTaskDataHandlerFunc) Handle(params GetTaskDataParams) middleware.Responder {
	return fn(params)
}

// GetTaskDataHandler interface for that can handle valid get task data params
type GetTaskDataHandler interface {
	Handle(GetTaskDataParams) middleware.Responder
}

// NewGetTaskData creates a new http.Handler for the get task data operation
func NewGetTaskData(ctx *middleware.Context, handler GetTaskDataHandler) *GetTaskData {
	return &GetTaskData{Context: ctx, Handler: handler}
}

/*GetTaskData swagger:route GET /tasks/{id}/data getTaskData

Get results of the work

*/
type GetTaskData struct {
	Context *middleware.Context
	Handler GetTaskDataHandler
}

func (o *GetTaskData) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTaskDataParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
