// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/crxfoz/seo_metrick_parser/server/api/models"
)

// GetTaskStatusOKCode is the HTTP code returned for type GetTaskStatusOK
const GetTaskStatusOKCode int = 200

/*GetTaskStatusOK OK

swagger:response getTaskStatusOK
*/
type GetTaskStatusOK struct {

	/*
	  In: Body
	*/
	Payload *models.Task `json:"body,omitempty"`
}

// NewGetTaskStatusOK creates GetTaskStatusOK with default headers values
func NewGetTaskStatusOK() *GetTaskStatusOK {

	return &GetTaskStatusOK{}
}

// WithPayload adds the payload to the get task status o k response
func (o *GetTaskStatusOK) WithPayload(payload *models.Task) *GetTaskStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get task status o k response
func (o *GetTaskStatusOK) SetPayload(payload *models.Task) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTaskStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTaskStatusNotFoundCode is the HTTP code returned for type GetTaskStatusNotFound
const GetTaskStatusNotFoundCode int = 404

/*GetTaskStatusNotFound Task id not found

swagger:response getTaskStatusNotFound
*/
type GetTaskStatusNotFound struct {
}

// NewGetTaskStatusNotFound creates GetTaskStatusNotFound with default headers values
func NewGetTaskStatusNotFound() *GetTaskStatusNotFound {

	return &GetTaskStatusNotFound{}
}

// WriteResponse to the client
func (o *GetTaskStatusNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetTaskStatusBadGatewayCode is the HTTP code returned for type GetTaskStatusBadGateway
const GetTaskStatusBadGatewayCode int = 502

/*GetTaskStatusBadGateway database is down

swagger:response getTaskStatusBadGateway
*/
type GetTaskStatusBadGateway struct {
}

// NewGetTaskStatusBadGateway creates GetTaskStatusBadGateway with default headers values
func NewGetTaskStatusBadGateway() *GetTaskStatusBadGateway {

	return &GetTaskStatusBadGateway{}
}

// WriteResponse to the client
func (o *GetTaskStatusBadGateway) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(502)
}
